### ISSUE TITLE
Enable Pin not working

### ISSUE THREAD

**Issue by eji133** [Droog71/CD74HC4067#1]
Hi,

I am learning on using Wokwi. And I utilize the multiplexer chip. 
I really appreciate for your product.

Quick question, I found out that the enable pin is not working on my project.
I try other examples from existing project with same result. 
when I connect the Enable pin to VCC, the IC still provide output.

Do you have any idea what when wrong?
could it be board.json line 33? Should it be "chip:E" instead of "chip:EN"?

thank you and best regards,

**Comment by Droog71** [comment]
> 

Yes, you are correct. In board.json, I should have put "chip:E".
Instead of submitting a pull request to the wokwi repo fixing the board.json file, I just renamed all instances of "chip:E" to "chip:EN" in the source code and chip.json files.
This way I could fix the problem on my end and just replace the chip.zip file right away.
I tested the enable pin after this change and everything seems to be working now.
Thank you for reporting this bug!
